common: &common
  adapter:  postgresql
  encoding: utf8
  pool:     5

local: &local
  <<: *common
  username: postgres

development:
  <<: *local
  database: hello_world_development

test:
  <<: *local
  database: hello_world_test
